AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
      
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,DELETE,PATCH'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin : "'*'"
        AllowCredentials: "'*'"

  TodoAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda.zip
      Handler: "haha"
      Runtime: provided
      Layers:
      - arn:aws:lambda:eu-central-1:426836788079:layer:Swift:12
      Policies:
      - DynamoDBReadPolicy:
          TableName: "SwiftLambdaTodos"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: "/{proxy+}"
            Method: ANY

